name: Helm Chart Update Check

on:
  push:
    branches:
      - test-1

env:
  HELM_PACKAGE_VERSION: 'v3.12.0'
  HELM_S3_PLUGIN_VERSION: 'v0.13.0'
  UPDATE_NEEDED: 'false'

jobs:
  helm-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: test-1

      - name: Install Helm
        run: |
          wget "https://get.helm.sh/helm-${{ env.HELM_PACKAGE_VERSION }}-linux-amd64.tar.gz"
          tar -xzvf "helm-${{ env.HELM_PACKAGE_VERSION }}-linux-amd64.tar.gz"
          sudo mv linux-amd64/helm /usr/local/bin/helm

      - name: Install jq
        run: |
          sudo apt-get update -y
          sudo apt-get install jq -y

      - name: Check and Update Helm chart versions
        id: check-versions
        run: |
          charts=$(jq -c '.charts[]' akash.json)

          for chart in $charts; do
            chart_name=$(echo "$chart" | jq -r '.chart')
            repository=$(echo "$chart" | jq -r '.repository')
            version=$(echo "$chart" | jq -r '.version')

            echo "Checking chart: $chart_name"
            echo "Repository: $repository"
            echo "Current Version: $version"

            helm repo add $chart_name $repository
            helm repo update

            latest_version=$(helm search repo $chart_name/$chart_name --versions | grep -oP '\d+\.\d+\.\d+' | head -n 1)

            if dpkg --compare-versions "$version" lt "$latest_version"; then
              echo -e "\n\033[34mVersion update needed for $chart_name. Current version: $version, Latest version: $latest_version\033[0m\n"
              # Update the version in akash.json
              jq --arg chart_name "$chart_name" --arg latest_version "$latest_version" \
                '(.charts[] | select(.chart == $chart_name) | .version) = $latest_version' akash.json > akash_updated.json && mv akash_updated.json akash.json
              echo "UPDATE_NEEDED=true" >> $GITHUB_ENV
              echo "$chart_name" >> "$GITHUB_ENV"  # Store chart name in GitHub environment variable
            else
              echo "No update needed for $chart_name. Current version: $version"
            fi
          done

      - name: Commit and Push changes if update needed
        if: env.UPDATE_NEEDED == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # Read chart names from GitHub environment variable
          charts=$(echo "$CHART_NAMES" | tr '\n' ' ')

          # Iterate over updated charts and create branches and push changes
          for chart_name in $charts; do
            git checkout -b "update-$chart_name"
            git add akash.json
            git commit -m "Update $chart_name version"
            git push origin HEAD:"update-$chart_name"
          done

