name: Helm Chart Update Check

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger this on
  pull_request:
    branches:
      - main  # Adjust to the branch you want to trigger this on

env:
  HELM_PACKAGE_VERSION: 'v3.12.0'
  HELM_S3_PLUGIN_VERSION: 'v0.13.0'

jobs:
  helm-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Helm
        run: |
          wget "https://get.helm.sh/helm-${{ env.HELM_PACKAGE_VERSION }}-linux-amd64.tar.gz"
          tar -xzvf "helm-${{ env.HELM_PACKAGE_VERSION }}-linux-amd64.tar.gz"
          sudo mv linux-amd64/helm /usr/local/bin/helm
          
      - name: List files for debugging
        run: |
          ls -la
          cat akash.yaml

      - name: Install jq
        run: |
          sudo apt-get update -y
          sudo apt-get install jq -y
