name: Helm Chart Update Check

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger this on
  pull_request:
    branches:
      - main  # Adjust to the branch you want to trigger this on

env:
  HELM_PACKAGE_VERSION: 'v3.12.0'
  HELM_S3_PLUGIN_VERSION: 'v0.13.0'

jobs:
  helm-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Helm
        run: |
          wget "https://get.helm.sh/helm-${{ env.HELM_PACKAGE_VERSION }}-linux-amd64.tar.gz"
          tar -xzvf "helm-${{ env.HELM_PACKAGE_VERSION }}-linux-amd64.tar.gz"
          mv linux-amd64/helm /usr/local/bin/helm

      - name: Add Helm repo and check versions
        run: |
          # Load variables from akash.yaml
          chart_name=$(jq -r '.chart' akash.yaml)
          repository=$(jq -r '.repository' akash.yaml)
          version=$(jq -r '.version' akash.yaml)

          # Add Helm repo
          helm repo add $chart_name $repository

          # Search for available versions
          latest_version=$(helm search repo $chart_name/$chart_name --versions | grep -oP '\d+\.\d+\.\d+' | head -n 1)

          # Compare versions
          if dpkg --compare-versions "$version" lt "$latest_version"; then
            echo "Version update needed for $chart_name. Current version: $version, Latest version: $latest_version"
            # You can add further actions here if an update is needed
          else
            echo "No update needed for $chart_name. Current version: $version"
          fi
